apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m1cezgn2w-python 
  janus-idp.io/tekton: m1cezgn2w-python
  backstage.io/kubernetes-id: m1cezgn2w-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m1cezgn2w-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml